// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckForUpdates():Promise<backend.UpdateInfo>;

export function CleanSubmodules(arg1:Array<string>):Promise<Array<string>>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadBackupToDirectory(arg1:backend.S3Credentials,arg2:string,arg3:string):Promise<string>;

export function DownloadBackupWithCreds(arg1:backend.S3Credentials,arg2:string,arg3:string):Promise<void>;

export function DumpMongoDatabase(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DumpMySQLDatabase(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DumpPostgresDatabase(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetBranches(arg1:string):Promise<Array<string>>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetDefaultBranch():Promise<string>;

export function GetLastCommits(arg1:Array<string>):Promise<Array<backend.Commit>>;

export function GetLastTags(arg1:string):Promise<backend.TagsResult>;

export function GitStatus(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallNpmDependencies(arg1:string,arg2:boolean):Promise<void>;

export function InstallSubmodules(arg1:string,arg2:Array<string>):Promise<void>;

export function ListBackupsWithCreds(arg1:backend.S3Credentials,arg2:string):Promise<Array<backend.BackupInfo>>;

export function ListMongoDatabases(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function ListMySQLDatabases(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function ListPostgresDatabases(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function ListSubmodules(arg1:string):Promise<Array<string>>;

export function NpmUpdateAction(arg1:string):Promise<void>;

export function PerformUpdate(arg1:string):Promise<void>;

export function RestoreMongoBackup(arg1:backend.S3Credentials,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function RestoreMySQLBackup(arg1:backend.S3Credentials,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function RestorePostgresBackup(arg1:backend.S3Credentials,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function RestoreS3Backup(arg1:backend.S3Credentials,arg2:backend.S3Credentials,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function SelectDownloadDirectory():Promise<string>;

export function TagAction(arg1:string,arg2:string):Promise<void>;

export function TestMySQLConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TransferMongoDatabase(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:boolean):Promise<void>;

export function TransferMySQLDatabase(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:boolean):Promise<void>;

export function TransferPostgresDatabase(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:boolean):Promise<void>;

export function UpdateGitSubmodules(arg1:string,arg2:Array<string>):Promise<void>;
