// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanSubmodules(arg1) {
  return window['go']['main']['App']['CleanSubmodules'](arg1);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetDefaultBranch() {
  return window['go']['main']['App']['GetDefaultBranch']();
}

export function GetLastCommits(arg1) {
  return window['go']['main']['App']['GetLastCommits'](arg1);
}

export function GetLastTags(arg1) {
  return window['go']['main']['App']['GetLastTags'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallNpmDependencies(arg1) {
  return window['go']['main']['App']['InstallNpmDependencies'](arg1);
}

export function InstallSubmodules(arg1) {
  return window['go']['main']['App']['InstallSubmodules'](arg1);
}

export function ListSubmodules(arg1) {
  return window['go']['main']['App']['ListSubmodules'](arg1);
}

export function NpmUpdateAction() {
  return window['go']['main']['App']['NpmUpdateAction']();
}

export function TagAction(arg1, arg2) {
  return window['go']['main']['App']['TagAction'](arg1, arg2);
}

export function UpdateGitSubmodules(arg1) {
  return window['go']['main']['App']['UpdateGitSubmodules'](arg1);
}
