// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CleanSubmodules(arg1) {
  return window['go']['main']['App']['CleanSubmodules'](arg1);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DownloadBackupWithCreds(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadBackupWithCreds'](arg1, arg2, arg3);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDefaultBranch() {
  return window['go']['main']['App']['GetDefaultBranch']();
}

export function GetLastCommits(arg1) {
  return window['go']['main']['App']['GetLastCommits'](arg1);
}

export function GetLastTags(arg1) {
  return window['go']['main']['App']['GetLastTags'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallNpmDependencies(arg1, arg2) {
  return window['go']['main']['App']['InstallNpmDependencies'](arg1, arg2);
}

export function InstallSubmodules(arg1, arg2) {
  return window['go']['main']['App']['InstallSubmodules'](arg1, arg2);
}

export function ListBackupsWithCreds(arg1, arg2) {
  return window['go']['main']['App']['ListBackupsWithCreds'](arg1, arg2);
}

export function ListSubmodules(arg1) {
  return window['go']['main']['App']['ListSubmodules'](arg1);
}

export function NpmUpdateAction(arg1) {
  return window['go']['main']['App']['NpmUpdateAction'](arg1);
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function RestoreMongoBackup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RestoreMongoBackup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RestoreS3Backup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RestoreS3Backup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TagAction(arg1, arg2) {
  return window['go']['main']['App']['TagAction'](arg1, arg2);
}

export function UpdateGitSubmodules(arg1, arg2) {
  return window['go']['main']['App']['UpdateGitSubmodules'](arg1, arg2);
}
