// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeBranch(arg1, arg2) {
  return window['go']['main']['App']['ChangeBranch'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CleanSubmodules(arg1) {
  return window['go']['main']['App']['CleanSubmodules'](arg1);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DownloadBackupWithCreds(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadBackupWithCreds'](arg1, arg2, arg3);
}

export function DumpMongoDatabase(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DumpMongoDatabase'](arg1, arg2, arg3, arg4, arg5);
}

export function DumpMySQLDatabase(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DumpMySQLDatabase'](arg1, arg2, arg3, arg4, arg5);
}

export function DumpPostgresDatabase(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DumpPostgresDatabase'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDefaultBranch() {
  return window['go']['main']['App']['GetDefaultBranch']();
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetLastCommits(arg1) {
  return window['go']['main']['App']['GetLastCommits'](arg1);
}

export function GetLastTags(arg1) {
  return window['go']['main']['App']['GetLastTags'](arg1);
}

export function GetPendingChanges(arg1) {
  return window['go']['main']['App']['GetPendingChanges'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallNpmDependencies(arg1, arg2) {
  return window['go']['main']['App']['InstallNpmDependencies'](arg1, arg2);
}

export function InstallSubmodules(arg1, arg2) {
  return window['go']['main']['App']['InstallSubmodules'](arg1, arg2);
}

export function ListBackupsWithCreds(arg1, arg2) {
  return window['go']['main']['App']['ListBackupsWithCreds'](arg1, arg2);
}

export function ListMongoDatabases(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListMongoDatabases'](arg1, arg2, arg3, arg4);
}

export function ListMySQLDatabases(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListMySQLDatabases'](arg1, arg2, arg3, arg4);
}

export function ListPostgresDatabases(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListPostgresDatabases'](arg1, arg2, arg3, arg4);
}

export function ListSubmodules(arg1) {
  return window['go']['main']['App']['ListSubmodules'](arg1);
}

export function NpmUpdateAction(arg1) {
  return window['go']['main']['App']['NpmUpdateAction'](arg1);
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function RestoreMongoBackup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RestoreMongoBackup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RestoreMySQLBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RestoreMySQLBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RestorePostgresBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RestorePostgresBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RestoreS3Backup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RestoreS3Backup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TagAction(arg1, arg2) {
  return window['go']['main']['App']['TagAction'](arg1, arg2);
}

export function TestMySQLConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMySQLConnection'](arg1, arg2, arg3, arg4);
}

export function TransferMongoDatabase(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['TransferMongoDatabase'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function TransferMySQLDatabase(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['TransferMySQLDatabase'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function TransferPostgresDatabase(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['TransferPostgresDatabase'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UpdateGitSubmodules(arg1, arg2) {
  return window['go']['main']['App']['UpdateGitSubmodules'](arg1, arg2);
}
